### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by trankil123** [babylonchain/babylon#545]
## Version
v0.8.4

## Steps to Reproduce

i was syncing and be on approximative 74312 blocs
then babylon stop and doesnt whant to restart

babylond.service: Main process exited, code=exited, status=1/FAILURE
babylond.service: Failed with result 'exit-code'.
babylond.service: Scheduled restart job, restart counter is at 2727.
Stopped Babylon daemon.
Started Babylon daemon.
6:30AM INF running app args=["start","--x-crisis-skip-assert-invariants"] module=cosmovisor path=/home/trankil/.babylond/cosmovisor/genesis/bin/babylond
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2aa3d55]
goroutine 1 [running]:
github.com/babylonchain/babylon/app.NewBabylonApp({0x3cac6e8, 0x5b3c500}, {0x3cc2800, 0xc000599640}, {0x0, 0x0}, 0x1, 0xc000b3f500, 0x0, 0x0, ...)
	github.com/babylonchain/babylon/app/app.go:380 +0x975
github.com/babylonchain/babylon/app.NewTmpBabylonApp()
	github.com/babylonchain/babylon/app/encoding.go:13 +0x1e5
github.com/babylonchain/babylon/cmd/babylond/cmd.NewRootCmd()
	github.com/babylonchain/babylon/cmd/babylond/cmd/root.go:51 +0x2a
main.main()
	github.com/babylonchain/babylon/cmd/babylond/main.go:16 +0x1c
Error: exit status 2
6:30AM ERR error="exit status 2" module=cosmovisor
babylond.service: Main process exited, code=exited, status=1/FAILURE
babylond.service: Failed with result 'exit-code'.
babylond.service: Scheduled restart job, restart counter is at 2728.

**Comment by trankil123** [comment]
increase disk storage
