### ISSUE TITLE
start service error

### ISSUE THREAD

**Issue by agideo-code** [babylonchain/babylon#552]
## Summary of Bug

Start failed

```
/root/go/bin/babylond start --trace --log_level trace

```

```
3:06AM DBG recursiveRemove key="P\x00\x00\x00\x00\x00\x01)\n" module=server node="Node{P:@ (86041, 12):[0 0 0 0 0 1 80 25 0 0 0 13]-[0 0 0 0 0 1 41 15 0 0 0 24] 5-3}#\n"
3:06AM DBG recursiveRemove key="P\x00\x00\x00\x00\x00\x01)\n" module=server node="Node{P:@ (86041, 13):[0 0 0 0 0 1 41 10 0 0 0 26]-[0 0 0 0 0 1 41 13 0 0 0 25] 3-2}#\n"
3:06AM DBG recursiveRemove key="P\x00\x00\x00\x00\x00\x01)\n" module=server node="Node{P:\n@ (76042, 26):[]-[] 1-0}#\n"
3:06AM DBG hash of all writes module=server workingHash=4CC8AED64C3FDB0D8DD62A27EFBDAAD588C9EF3CBBDDEE1BE6234CB614894210
3:06AM INF finalized block block_app_hash=4CC8AED64C3FDB0D8DD62A27EFBDAAD588C9EF3CBBDDEE1BE6234CB614894210 height=86042 module=consensus num_txs_res=36 num_val_updates=0
3:06AM INF executed block app_hash=4CC8AED64C3FDB0D8DD62A27EFBDAAD588C9EF3CBBDDEE1BE6234CB614894210 height=86042 module=consensus
3:06AM INF Closing application.db module=server
3:06AM INF Closing snapshots/metadata.db module=server
panic: version does not exist

goroutine 1 [running]:
cosmossdk.io/store/iavl.(*Store).Commit(0xc00397f020?)
        cosmossdk.io/store@v1.0.2/iavl/store.go:127 +0xd4
cosmossdk.io/store/rootmulti.commitStores(0x1501a, 0xc002041050, 0xc0206a6878?)
        cosmossdk.io/store@v1.0.2/rootmulti/store.go:1196 +0x14e
cosmossdk.io/store/rootmulti.(*Store).Commit(0xc001559600)
        cosmossdk.io/store@v1.0.2/rootmulti/store.go:482 +0x1a5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc00120efc0)
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/baseapp/abci.go:930 +0x2e2
github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.Commit(...)
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/cmt_abci.go:56
github.com/cometbft/cometbft/abci/client.(*localClient).Commit(0x80?, {0x3b4f1a8?, 0x59e7440?}, 0xc0206a7bc8?)
        github.com/cometbft/cometbft@v0.38.5/abci/client/local_client.go:113 +0xd0
github.com/cometbft/cometbft/proxy.(*appConnConsensus).Commit(0xc001513800, {0x3b4f1a8, 0x59e7440})
        github.com/cometbft/cometbft@v0.38.5/proxy/app_conn.go:109 +0x165
github.com/cometbft/cometbft/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc00193b690, 0x6}}, {0xc00193b696, 0xa}, 0x1, 0x1501a, {{0xc003008320, ...}, ...}, ...}, ...)
        github.com/cometbft/cometbft@v0.38.5/state/execution.go:393 +0x213
github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc00193b690, 0x6}}, {0xc00193b696, 0xa}, 0x1, 0x1501a, {{0xc003008320, ...}, ...}, ...}, ...)
        github.com/cometbft/cometbft@v0.38.5/state/execution.go:279 +0x1050
github.com/cometbft/cometbft/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc00193b690, 0x6}}, {0xc00193b696, 0xa}, 0x1, 0x15019, {{0xc0019efd80, ...}, ...}, ...}, ...)
        github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:534 +0x257
github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocksWithContext(_, {_, _}, {{{0xb, 0x0}, {0xc00193b690, 0x6}}, {0xc00193b696, 0xa}, 0x1, ...}, ...)
        github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:433 +0x79a
github.com/cometbft/cometbft/consensus.(*Handshaker).HandshakeWithContext(0xc0206a93b0, {0x3b4f100, 0xc00281e7d0}, {0x3b6dad0?, 0xc00117ce00?})
        github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:274 +0x478
github.com/cometbft/cometbft/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x0}, {0xc00193b690, 0x6}}, {0xc00193b696, 0xa}, ...}, ...)
        github.com/cometbft/cometbft@v0.38.5/node/setup.go:182 +0x1a9
github.com/cometbft/cometbft/node.NewNodeWithContext({0x3b4f100, 0xc00281e7d0}, 0xc0015d08c0, {0x3b39e60, 0xc00267eaa0}, 0xc000b4a490, {0x3b13020, 0xc004814450}, 0x1?, 0x355dd58, ...)
        github.com/cometbft/cometbft@v0.38.5/node/node.go:350 +0x5b7
github.com/cosmos/cosmos-sdk/server.startCmtNode({0x3b4f100, 0xc00281e7d0}, 0xc0015d08c0, {0x3b8f900?, 0xc000fc2c00}, 0xc001136e60)
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:402 +0x43f
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{{0xc0023ceda0, 0xb}, 0x0, {0xc0023cf220, 0x6}, {0xc0023cfec0, 0x3}, {0x33c7345, 0x2}, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:348 +0x188
github.com/cosmos/cosmos-sdk/server.start(_, {{0x0, 0x0, 0x0}, {0x3b719b8, 0xc001ac4e40}, 0x0, {0xc000e8a060, 0xa}, {0x3b8f9c8, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:266 +0x2f3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2.1()
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:175 +0x5e
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile(0xc001136e60, 0xc00111f810)
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:600 +0x1b3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2(0xc001ba6000?, {0xc001a19aa0?, 0x0?, 0x3?})
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:174 +0x212
github.com/spf13/cobra.(*Command).execute(0xc00160b800, {0xc001a19a10, 0x3, 0x3})
        github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc00239a300)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc00111ff30?, {0x0, 0x0}, {0xc000dd0020, 0xf})
        github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/cmd/execute.go:34 +0x187
main.main()
        github.com/babylonchain/babylon/cmd/babylond/main.go:18 +0x38
# /root/go/bin/babylond start --trace --log_level trace
```

## Version

v0.8.4

**Comment by Gardelll** [comment]
Maybe your LevelDB metadata is corrupted, you can try this to rebuild the metadata.

```shell
cd ~/.babylond/data/application.db
# write empty metadata
echo 'Vvm4+BwAAQEabGV2ZWxkYi5CeXRld2lzZUNvbXBhcmF0b3KknIu+CAABAgMJAAMEBAA=' > `cat CURRENT`
```

(backup your MANIFEST before override)

**Comment by halink0803** [comment]
@Gardelll I think your response is not sufficient, about how to backup MANIFEST (I think). I only backup the MANIFEST file and the CURRENT file. After, I follow your suggestion, the log show failed. I bring back the MANIFEST file and the old current, now it show the DB is corrupt as the file is missing. I guess I have to start all over again 😢

**Comment by vitsalis** [comment]
Seems to not be properly setup. Closing this due to inactivity and testnet-3 being sunsetted.
